[package]
name = "rslice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom_stl = "0.2.2"
clap = "2.33.3"
tungstenite = "0.16.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"